- name: Update and install system packages
  include_tasks: packages.yml

- name: Install and configure Python environment
  include_tasks: python_setup.yml

- name: Create Unix group and user for OpenFisca Web API
  include_tasks: user_setup.yml

- name: Set up OpenFisca Web API
  include_tasks: web_api_setup.yml

- name: Set up systemd service for OpenFisca Web API
  include_tasks: systemd.yml

- name: Check that OpenFisca Web API is actually started
  include_tasks: health_check.yml
