- name: Create Unix group for OpenFisca Web API
  ansible.builtin.group:
    name: "{{ unix_group_name }}"
    state: present

- name: Create Unix user for OpenFisca Web API
  ansible.builtin.user:
    name: "{{ unix_user_name }}"
    group: "{{ unix_group_name }}"
    shell: /bin/bash
  register: unix_user
