base_url_path: /
env_file: /etc/openfisca/openfisca-web-api-fr.env
host_name: localhost
host: 127.0.0.1
http_port: 8000
nb_workers: 2
systemd_service_file: /etc/systemd/system/openfisca-web-api-fr.service
unix_group_name: openfisca
unix_user_name: openfisca-api
welcome_message: Welcome to the OpenFisca Web API. This instance runs the OpenFisca-France country package.

# Optional: auto-update

enable_autoupdate: yes
autoupdate_unix_group_name: "{{ unix_group_name }}"
autoupdate_unix_user_name: openfisca-ops
autoupdate_ops_branch_name: install-api-with-ansible
autoupdate_ops_repo_url: https://github.com/openfisca/openfisca-ops.git

# Optional: SSL certificate
# An SSL certificate is issued from Let's Encrypt if `enable_ssl` and `letsencrypt_email` are both defined.
enable_ssl: no
letsencrypt_email: null
letsencrypt_environment: staging  # switch to `production` after testing to avoid reaching your Let's Encrypt quota

# Optional: Matomo tracker
# See more on https://github.com/openfisca/openfisca-tracker
matomo_url: null
matomo_site_id: null
matomo_token: "{{ lookup('env','MATOMO_TOKEN') }}"
matomo_enabled: "{{ matomo_site_id and matomo_token and matomo_url }}"
