# Inventory variables overloading playbook default variables (cf roles/openfisca-api/defaults/main.yml)

host_name: openfisca.jailbreak.paris

# SSL certificate
enable_ssl: yes
letsencrypt_email: christophe.benz@jailbreak.paris
letsencrypt_environment: "production"
