python_version: "3.11" # must be string, not a number

app_host: 127.0.0.1
app_port: 8000
country_module: openfisca_country_template
country_package: OpenFisca-Country-Template
nb_workers: 2
welcome_message: Welcome to an instance of the OpenFisca Web API for the {{ country_package }} country package.

# Optional: Matomo tracker
# See more on https://github.com/openfisca/openfisca-tracker
matomo_url: null
matomo_site_id: null
matomo_token: "{{ lookup('env','MATOMO_TOKEN') }}"

# Fully managed by Ansible, you should not need to edit this unless you have a naming collision
env_file: /etc/openfisca/openfisca-web-api.env
systemd_service_file_name: openfisca-web-api.service
unix_group_name: openfisca
unix_user_name: openfisca-api
venv_dir: venv  # relative to the home directory
