all:
  hosts:
    vps-60ea1664.openfisca.org:
      ansible_user: root

      base_path: /latest
      country_code: fr
      country_module: openfisca_france
      country_package: OpenFisca-France
      host_name: api.fr.openfisca.org
      port: 8001

      autoupdate_inventory_file: ansible/inventories/api.fr.openfisca.org.yml

      letsencrypt_email: contact@openfisca.org
      letsencrypt_environment: production

      matomo_url: https://stats.data.gouv.fr/piwik.php
      matomo_site_id: 4
