all:
  hosts:
    vps-60ea1664.openfisca.org:
      ansible_user: root

      base_path: /api/latest
      host_name: api.fr.openfisca.org

      letsencrypt_email: contact@openfisca.org
      letsencrypt_environment: production
