# This file is used by the auto-update feature of the openfisca_api_fr Ansible role.

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: root

      base_path: /api/latest
      host_name: api.fr.openfisca.org
      autoupdate_inventory_file: ansible/inventories/api.fr.openfisca.org-local.yml

      letsencrypt_email: contact@openfisca.org
      letsencrypt_environment: production
