openfisca_api:
  hosts:
    openfisca.jailbreak.paris:
      ansible_user: root
      # adjust the variables defined in `ansible/roles/openfisca_api_fr/defaults/main.yml` below:
      host_name: openfisca.jailbreak.paris
      enable_ssl: yes
      letsencrypt_email: contact@openfisca.org
      letsencrypt_environment: "production"
