# Optional: auto-update this playbook upon execution
# To enable this feature, set `autoupdate_inventory_file` to a file path, absolute or relative to the clone directory of `autoupdate_ops_repo_url`.
autoupdate_inventory_file: null
autoupdate_ops_branch_name: master
autoupdate_ops_repo_url: https://github.com/openfisca/openfisca-ops.git

# Fully managed by Ansible, you should not need to edit this unless you have a naming collision
autoupdate_systemd_service_file_name: openfisca-web-api-autoupdate.service
autoupdate_systemd_timer_file_name: openfisca-web-api-autoupdate.timer
unix_group_name: openfisca
unix_user_name: openfisca-api
# Those directories are relative to the home directory of the Unix user:
openfisca_ops_clone_relative_dir: openfisca-ops
