- name: Set up auto-update
  tags:
    - auto-update
  when: autoupdate_inventory_file
  block:
    - name: Add the "ansible" PPA
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible
        state: present

    - name: Install Ubuntu packages required for auto-update
      ansible.builtin.apt:
        install_recommends: no
        name:
          - ansible
          - git
        state: present
        update_cache: no

    - name: Define a directory for openfisca-ops
      ansible.builtin.set_fact:
        openfisca_ops_clone_path: "{{ unix_user.home }}/{{ openfisca_ops_clone_dir }}"

    - name: Clone or update openfisca-ops
      ansible.builtin.git:
        repo: "{{ autoupdate_ops_repo_url }}"
        dest: "{{ openfisca_ops_clone_path }}"
        version: "{{ autoupdate_ops_branch_name }}"
      become_user: "{{ unix_user_name }}"

    - name: Set up the systemd service
      ansible.builtin.template:
        src: openfisca-web-api-autoupdate.service.j2
        dest: "/etc/systemd/system/{{ autoupdate_systemd_service_file_name }}"

    - name: Set up the systemd timer
      ansible.builtin.copy:
        src: openfisca-web-api-autoupdate.timer
        dest: "/etc/systemd/system/{{ autoupdate_systemd_timer_file_name }}"

    - name: Enable the systemd timer
      ansible.builtin.systemd:
        name: "{{ autoupdate_systemd_timer_file_name }}"
        daemon_reload: yes
        enabled: yes
        state: started
