- name: Update the cache of Ubuntu packages
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - apt-update-cache

- name: Install Ubuntu packages
  block:
    - name: Enable installing Personal Package Archives (PPA) with apt
      ansible.builtin.apt:
        install_recommends: no
        name:
          - gnupg
        state: present
        update_cache: no

    - name: Enable installing arbitrary Python versions
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa  # See more on https://tooling.bennuttall.com/deadsnakes/
        state: present

    - name: Install the OpenFisca-supported Python version  # See https://github.com/openfisca/openfisca-core#environment
      ansible.builtin.apt:
        install_recommends: no
        name:
          - acl # Provides "setfacl" command, used by Ansible to become another Unix user
          - gcc
          - nginx
          - python3.7
          - python3.7-dev
          - python3-virtualenv
        state: present
        update_cache: no

- name: Create a Unix group for the OpenFisca Web API
  ansible.builtin.group:
    name: "{{ unix_group_name }}"
    state: present

- name: Create a Unix user for the OpenFisca Web API
  ansible.builtin.user:
    name: "{{ unix_user_name }}"
    group: "{{ unix_group_name }}"
    shell: /bin/bash
  register: unix_user

- name: Define a directory to store the virtualenv of OpenFisca Web API
  ansible.builtin.set_fact:
    venv_dir: "{{ unix_user.home }}/venv"

- name: Install the latest version of OpenFisca Web API in the virtualenv with OpenFisca-France
  ansible.builtin.pip:
    # Using chdir to solve an error as explained by [this comment](https://github.com/ansible/ansible/issues/22967#issuecomment-500604054)
    chdir: "{{ venv_dir }}"
    name:
      - OpenFisca-Core[web-api]
      - OpenFisca-France
    state: latest
    virtualenv: "{{ venv_dir }}"
    virtualenv_python: python3.7
    virtualenv_site_packages: no
  become_user: "{{ unix_user_name }}"
  notify: Reload nginx

- name: Set up the systemd service
  block:
    - name: Create the directory receiving the environment file
      ansible.builtin.file:
        path: "{{ env_file | dirname }}"
        state: directory
        mode: "0755"

    - name: Copy the environment file referenced by the systemd service
      ansible.builtin.template:
        backup: yes
        src: systemd/openfisca-web-api-fr.env.j2
        dest: "{{ env_file }}"

    - name: Copy the systemd service file
      ansible.builtin.template:
        backup: yes
        src: systemd/openfisca-web-api-fr.service.j2
        dest: "{{ systemd_service_file }}"

    - name: Enable and start the systemd service
      ansible.builtin.systemd:
        daemon_reload: yes
        enabled: yes
        state: restarted
        name: openfisca-web-api-fr

- name: Check that OpenFisca Web API is actually started
  ansible.builtin.uri:
    return_content: yes
    status_code: 300
    timeout: 120
    url: "http://localhost:{{ port }}"
  register: this
  until: this.status == 300
  retries: 5 # times
  delay: 5 # seconds

- name: Copy the nginx vhost file to the sites-available directory of Nginx
  ansible.builtin.template:
    backup: yes
    src: nginx/openfisca-web-api.conf.j2
    dest: "/etc/nginx/sites-available/{{ host_name }}.conf"

- name: Link the nginx vhost file to the sites-enabled directory of Nginx
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ host_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ host_name }}.conf"
    state: link
  notify: Reload nginx

- name: Set SSL up
  when: enable_ssl and letsencrypt_email
  block:
    - name: Install Certbot and its Nginx plugin
      ansible.builtin.apt:
        install_recommends: no
        name:
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: no

    - name: Handle staging environment
      when: letsencrypt_environment == "staging"
      block:
        - name: Display message when staging environment is used
          ansible.builtin.debug:
            msg: Let's Encrypt staging environment will be used

        - name: Define certbot --staging option
          ansible.builtin.set_fact:
            certbot_staging_option: "--staging"

    - name: Issue or renew an SSL certificate with Let's Encrypt
      ansible.builtin.command: >
        certbot
        --non-interactive --email {{ letsencrypt_email }} --agree-tos
        --nginx --redirect
        --domains {{ host_name }} --keep-until-expiring
        {{ certbot_staging_option | default() }}
      become_user: root
      register: certbot_result

    - name: Enable HTTP/2
      ansible.builtin.lineinfile:
        backrefs: yes
        line: '\1\2 http2;\3'
        path: "/etc/nginx/sites-available/{{ host_name }}.conf"
        regexp: "^(.*)(listen 443 ssl);(.+)$"
      notify: Reload nginx
      tags:
        - http2

- name: Set up auto-update
  tags:
    - auto-update
  when: enable_autoupdate
  block:
    - name: Add the "ansible" PPA
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible
        state: present

    - name: Install Ubuntu packages required for auto-update
      ansible.builtin.apt:
        install_recommends: no
        name:
          - ansible
          - git
        state: present
        update_cache: no

    - name: Create the Unix group for auto-update
      ansible.builtin.group:
        name: "{{ autoupdate_unix_group_name }}"
        state: present

    - name: Create the Unix user for auto-update
      ansible.builtin.user:
        name: "{{ autoupdate_unix_user_name }}"
        group: "{{ autoupdate_unix_group_name }}"
        shell: /bin/bash
      register: autoupdate_unix_user

    - name: Clone or update the "openfisca-ops" Git repository
      ansible.builtin.git:
        repo: "{{ autoupdate_ops_repo_url }}"
        dest: "{{ autoupdate_unix_user.home }}/openfisca-ops"
        version: "{{ autoupdate_ops_branch_name }}"
      become_user: "{{ autoupdate_unix_user_name }}"

    - name: Copy the cron job definition
      ansible.builtin.template:
        backup: yes
        src: cron.d/openfisca-api-fr.j2
        dest: /etc/cron.d/openfisca-api-fr
